//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaoDien.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public string ID_Thanh_toán { get; set; }
        public string ID_Order { get; set; }
        public int Tổng_tiền { get; set; }
        public int Tiền_nhận_vào { get; set; }
        public int Tiền_thừa { get; set; }
        public System.DateTime Thời_gian_thanh_toán { get; set; }
        public string ID_Kì_hạn { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Period Period { get; set; }
    }
}
