//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaoDien.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Period
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Period()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public string ID_Kì_hạn { get; set; }
        public string Tên_kì_hạn { get; set; }
        public System.DateTime Thời_gian_bắt_đầu_kì_hạn { get; set; }
        public System.DateTime Thời_gian_kết_thúc_kì_hạn { get; set; }
        public System.DateTime Thời_gian_chung_của_kì_hạn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
