//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaoDien.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_WDay
    {
        public string ID_WDay { get; set; }
        public string ID_Account { get; set; }
        public Nullable<System.DateTime> Shift_Start_Time { get; set; }
        public Nullable<System.DateTime> Shift_End_Time { get; set; }
        public Nullable<int> Salary_Shift { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
